server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    autoindex off;
    add_header X-Content-Type-Options nosniff always;
    location /courses/ {
        try_files $uri =404;
        expires 1h;
    }
    location / { return 404; }
}
