SET NAMES utf8mb4;
USE learnhub;

ALTER TABLE course MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号';
ALTER TABLE course_chapter MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号';
ALTER TABLE course_lesson MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号';
